// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe7a2MbHiLTbNgVkQziNrA56LzM7CEjZU',
    appId: '1:647707196901:web:7d09780460e6a406b6030c',
    messagingSenderId: '647707196901',
    projectId: 'furnituresellingapp-822cf',
    authDomain: 'furnituresellingapp-822cf.firebaseapp.com',
    storageBucket: 'furnituresellingapp-822cf.appspot.com',
    measurementId: 'G-NBRFG2XJ00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDq4s-trIzcsdvWUj8XV-p7yJhP5rvNZ4',
    appId: '1:647707196901:android:46662285318fb769b6030c',
    messagingSenderId: '647707196901',
    projectId: 'furnituresellingapp-822cf',
    storageBucket: 'furnituresellingapp-822cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3MtIhMP3NpQNd2LgtSZiv-OEAyi4UVlM',
    appId: '1:647707196901:ios:c2e0f42028f5ce10b6030c',
    messagingSenderId: '647707196901',
    projectId: 'furnituresellingapp-822cf',
    storageBucket: 'furnituresellingapp-822cf.appspot.com',
    androidClientId: '647707196901-dpqm02ntr9a1grees2eb0q8fdt74qbch.apps.googleusercontent.com',
    iosClientId: '647707196901-5kegfqeefin9h766a538k8d0n2fhctbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.houtAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3MtIhMP3NpQNd2LgtSZiv-OEAyi4UVlM',
    appId: '1:647707196901:ios:9b57fcd4b860cf2bb6030c',
    messagingSenderId: '647707196901',
    projectId: 'furnituresellingapp-822cf',
    storageBucket: 'furnituresellingapp-822cf.appspot.com',
    androidClientId: '647707196901-dpqm02ntr9a1grees2eb0q8fdt74qbch.apps.googleusercontent.com',
    iosClientId: '647707196901-su3gd2kmsit39b8gers202hai5t7sgq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.houtAdmin.RunnerTests',
  );
}
